apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lvs499jkr-python-gitops
  description: This is GitOps manifest for lvs499jkr-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=lvs499jkr-python
    backstage.io/kubernetes-id: lvs499jkr-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: lvs499jkr-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:lvs499jkr-python
