apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lvs499jkr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lvs499jkr-python 
  name: lvs499jkr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lvs499jkr-python 
